version: "3"
services:
  mysql:
    image: "mysql:latest"
  my-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myDB

  my-db-app:
    build: .
    ports:
      - "3307:3307"
